import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Videoconference } from '../models/videoconferences';

@Injectable({
  providedIn: 'root'
})
export class OnlineWorkshopsService {

  private videoconferences: any[] = [
    {
      name: "claves para el desarrollo d ecompetencia en un contexto hibrido",
      speaker: "Mg. Ana Lucía Fernández Castillo",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "CONECTADOS Ministerio de Educación del Perú",
      date: "03/2022",
      hour: "",
      state: false,
      link: "https://www.minedu.gob.pe/conectados/webinars.php",
    },
    {
      name: "preparando el retorno a clases: retos  para afrontar  la presencialidad y semipresencilidad en las universidades",
      speaker: "Mg. Rocío Quispe Rupaylla",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "CONECTADOS Ministerio de Educación del Perú",
      date: "02/2022",
      hour: "",
      state: false,
      link: "https://www.minedu.gob.pe/conectados/webinars.php",
    },

    {
      name: "Coaching docente: un nuevo modelo para la interacción con los alumnos",
      speaker: "Ana María Quintanilla",
      nationality: "México",
      category: "Educación",
      organizedBy: "Pontificia Universidad Católica del Perú",
      date: "29/10/2021",
      hour: "",
      state: false,
      link: "https://zoom.us/meeting/register/tJUvfuuuqD8uG9dZuVGmgaWVQnO6q-Zvg4Mw",
    },
    {
      name: "Como encontrar la mejor revista para publicar un artículo científico",
      speaker: "Dra. Thais Vick",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "CONECTADOS Ministerio de Educación del Perú",
      date: "30/03/2021",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=2813650198889484&ref=watch_permalink",
    },
    {
      name: "Asegurando la continuidad académica de las mujeres en la Educación Superior",
      speaker: "Dra Carla Sagastegui",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "CONECTADOS Ministerio de Educación del Perú",
      date: "09/03/2021",
      hour: "",
      state: false,
      link: "https://www.facebook.com/mineduperu/videos/214581467124929",
    },
    {
      name: "Webinar Digitalización acelerada: lo que la pandemia le enseñó a la educación (parte 2 de 2)",
      speaker: "",
      nationality: "",
      category: "Educación",
      organizedBy: "Banco Interamericano de Desarrollo",
      date: "10/03/2021",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=pKZ1f6dRUBM",
    },
    {
      name: "Webinar Digitalización Acelerada: lo que la pandemia le enseñó a la educación (día 1 de 2)",
      speaker: "",
      nationality: "",
      category: "Educación",
      organizedBy: "Banco Interamericano de Desarrollo",
      date: "09/03/2021",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=M6aPRSt6gGI",
    },
    {
      name: "Educadores 2021: Adaptándonos a la virtualidad y evolución de los estudiantes con Angélica Natera, Directora Ejecutiva de Laspau",
      speaker: "Dra, Angelica Natera",
      nationality: "Chile",
      category: "Educación",
      organizedBy: "Laspau",
      date: "08/12/2020",
      hour: "",
      state: false,
      link: "https://vimeo.com/488553836",
    },
    {
      name: "Cómo invertir su clase en línea cuando el mundo está invertido ",
      speaker: "Dr. Eric Mazur",
      nationality: "Chile",
      category: "Educación",
      organizedBy: "Colab Laspau",
      date: "10/04/2020",
      hour: "",
      state: false,
      link: "https://colab.laspau.org/es/articulos/eric-mazur-como-invertir-su-clase-en-linea-cuando-el-mundo-esta-invertido-webinar/",
    },
    {
      name: "Herramientas digitales y secuencia didáctica en clase",
      speaker: "Jorge Bossio Montes De Oca, Alvaro Tobaru Hamada, Magna Guerreo Celis, Antonio Andrade Pinelo",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "Ministerio de Educación",
      date: "21/07/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=292920861948206&ref=watch_permalink",
    },
    {
      name: "Metodologías de la enseñanza",
      speaker: "Gumercindo Bartra",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "Ministerio de Educación",
      date: "16/06/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=604981423770178&ref=watch_permalink",
    },
    {
      name: "Herramientas y modelos para el seguimiento y evaluación del aprendizaje en entornos virtuales",
      speaker: "Ciclo de lo Presencial a lo Virtual",
      nationality: "España",
      category: "Educación",
      organizedBy: "UNIR",
      date: "09/07/2020",
      hour: "13:00 a 14:15",
      state: false,
      link: "https://unir.adobeconnect.com/pqvanby173ay/",
    },
    {
      name: "Herramientas de enseñanza y  gestión académica virtuales",
      speaker: "Ciclo de lo Presencial a lo Virtual",
      nationality: "España",
      category: "Educación",
      organizedBy: "UNIR",
      date: "07/07/2020",
      hour: "13:00 a 14:15",
      state: false,
      link: "https://unir.adobeconnect.com/pcex1n1gcu71/",
    },
    {
      name: "Metodología para aprender online y enseñar de manera eficaz",
      speaker: "Ciclo de lo Presencial a lo Virtual",
      nationality: "España",
      category: "Educación",
      organizedBy: "UNIR",
      date: "02/07/2020",
      hour: "",
      state: false,
      link: "https://unir.adobeconnect.com/pshzl6w53nd1/",
    },
    {
      name: "Como organizar un plan eficaz de transición de la formación presencial a la virtual",
      speaker: "Ciclo de lo Presencial a lo Virtual",
      nationality: "España",
      category: "Educación",
      organizedBy: "UNIR",
      date: "30/06/2020",
      hour: "",
      state: false,
      link: "https://unir.adobeconnect.com/piri9wjo2t7x/",
    },
    {
      name: "Recursos y estrategias para el aprendizaje en linea",
      speaker: "Dra. Claudia Pontón Ramos",
      nationality: "Mexico",
      category: "Educación",
      organizedBy: "INEDU",
      date: "12/06/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=879479509204838&ref=watch_permalink",
    },
    {
      name: "Evaluación del aprendizaje en entornos virtuales y remotos",
      speaker: "Dr. Adolfo Ignacio Calderón Flores",
      nationality: "Brasil",
      category: "Educación",
      organizedBy: "INEDU",
      date: "05/06/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=682591869246352&ref=watch_permalink",
    },
    {
      name: "Evaluación del aprendizaje en entornos virtuales y remotos",
      speaker: "Dr. Francisco José García Peñalvo",
      nationality: "España",
      category: "Educación",
      organizedBy: "INEDU",
      date: "03/06/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=607747663167940&ref=watch_permalink",
    },
    {
      name: "Evaluación del aprendizaje en entornos virtuales y remotos",
      speaker: "Dra. Frida Díaz Barriga",
      nationality: "Mexico",
      category: "Educación",
      organizedBy: "INEDU",
      date: "01/06/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/watch/live/?v=258652365212130&ref=watch_permalink",
    },
    {
      name: "Diseño y desarrollo de sesiones online",
      speaker: "Dra. Juliana Elisa Raffaglelli",
      nationality: "España",
      category: "Educación",
      organizedBy: "INEDU",
      date: "29/05/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/tvunsa/videos/3519694388045792/",
    },
    {
      name: "Diseño y desarrollo de sesiones online",
      speaker: "Dr. Francisco Javier Vázquez Ramos",
      nationality: "España",
      category: "Educación",
      organizedBy: "INEDU",
      date: "27/05/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/tvunsa/videos/277792936692614/",
    },
    {
      name: "Diseño y desarrollo de sesiones online",
      speaker: "Dr. Ángel Hernando Gómez",
      nationality: "España",
      category: "Educación",
      organizedBy: "INEDU",
      date: "25/05/2020",
      hour: "",
      state: false,
      link: "https://www.facebook.com/tvunsa/videos/700496077187054/",
    },
    /*{
      name: "Evaluaciones",
      speaker: "Mg. Elizabeth Vidal",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "DUTIC TVUNSA",
      date: "30/05/2020",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=CpQGpltSLa4",
    },
    {
      name: "Estudiantes, foros y tareas",
      speaker: "",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "DUTIC TVUNSA",
      date: "30/05/2020",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=CpQGpltSLa4",
    },
    {
      name: "Comunicación: foros, mensajes, videollamadas",
      speaker: "Sr. Jorge Vizcarra",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "DUTIC TVUNSA",
      date: "30/05/2020",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=2duDsc5rr_U",
    }, 
    {
      name: "Compartiendo Material",
      speaker: "Mg. Elizabeth Vidal",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "DUTIC TVUNSA",
      date: "30/05/2020",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=bFku0u1i888",
    },
    {
      name: "Lineamientos y Acceso al Aula Virtual",
      speaker: "Mg. Elizabeth Vidal",
      nationality: "Perú",
      category: "Educación",
      organizedBy: "DUTIC TVUNSA",
      date: "30/05/2020",
      hour: "",
      state: false,
      link: "https://www.youtube.com/watch?v=4YUV9j2UYXI",
    },*/
    
  ];

  /*
  {
      name: "Recursos y estrategias para el aprendizaje en línea",
      speaker: "Dra. María Soledad Ramírez Montoya",
      nationality: "México",
      category: "Educación",
      organizedBy: "INEDU",
      date: "08/05/2020",
      hour: "",
      state: false,
      link: "",
    },
    {
      name: "Recursos y estrategias para el aprendizaje en línea",
      speaker: " Dra. Nora Liliana Dari",
      nationality: "Argentina",
      category: "Educación",
      organizedBy: "INEDU",
      date: "10/05/2020",
      hour: "13:00 a 14:15",
      state: false,
      link: "",
    },
    {
      name: "Recursos y estrategias para el aprendizaje en línea",
      speaker: "Dra. Claudia Pontón Ramos",
      nationality: "México",
      category: "Educación",
      organizedBy: "INEDU",
      date: "12/05/2020",
      hour: "13:00 a 14:15",
      state: false,
      link: "",
    },
  */
  constructor() { }

  getVideoconferencesList(): Observable<any> {
    return of(this.videoconferences);
  }

  searchByCategory(search:string){
    let videoCategoryArray: Videoconference[] = [];

      if (search == "education"){
        videoCategoryArray = this.videoconferences.filter(videoconference => videoconference.category == "Educación")
        return videoCategoryArray;
      }
  }
  searchByCountry(search:string){
    let videoCategoryArray: Videoconference[] = [];

      if (search == "mexico"){
        videoCategoryArray = this.videoconferences.filter(videoconference => videoconference.nationality == "México")
        return videoCategoryArray;
      }
  }
}
